### ISSUE TITLE
Just tried to install and run monkalot and here are my thoughts ... 

### ISSUE THREAD

**Issue by ghostduck** [NMisko/monkalot#2]
After installing .NET framework >4.5.1 and C++ v14 and Windows 8.1 SDK on my machine, I can finally install twisted.

After that, I tried to run monaklot.py and I found there more packages are needed.

pip install pyparsing
pip install cleverwrap
pip install colorlog

I think it can be helpful If you can add a small text file suggesting all these packages and those Microsoft things are needed (if you are on Windows).

Now I can try to figure out how to make monkalot works locally ... (Keep seeing "Lose connection, reconnecting" in red now) monkaS

**Comment by ghostduck** [comment]
Nevermind, just saw requirements.txt ... 

If you can add "check requirements.txt for the required packages" in README then it could have saved some time FailFish

**Comment by NMisko** [comment]
For Python packages there's often a _requirements.txt_ or _setup.py_ file that contains necessary packages. You can install all of them using `pip install -r requirements.txt`. I'll also add it to the README. Make sure you filled out the configuration in _bot_config.json_ if you keep on getting the "Lose connection, reconnecting" error.
