### ISSUE TITLE
'TwitchBot' object has no attribute 'port' in bot/bot.py

### ISSUE THREAD

**Issue by ghostduck** [NMisko/monkalot#3]
I have that error when I try to start monkalot. I can't see anywhere to give the port parameter to TwitchBot.
I have to manually add 
`self.port = None` 
before 
`if self.port is not None:`

 to prevent the error. Any ideas? Or do I setup anything wrong? 
I start without inputting a port since I don't plan to use web service in my test run, not sure if related or not.

**Comment by CodeMonkey3451** [comment]
Definition of port was missing in bot.py. Fixed
