### ISSUE TITLE
Counted emotes don't get updated

### ISSUE THREAD

**Issue by NMisko** [NMisko/monkalot#37]
When a new (bttv) emote gets added, it doesn't get counted, meaning its counter is always 0.
Expected behaviour: In regular intervals, new emotes should be added to the count list.

**Comment by CodeMonkey3451** [comment]
We have multiple commands which depend on API calls like this. For example the `StreamInfo` command also uses this API. The `GuessMinionGame` commands relies on the Hearthstone card API, etc.

Maybe we should add a routine which renews all API's maybe hourly or once a day?

**Comment by NMisko** [comment]
This isn't necessary e.g. for the Hearthstone cards or the BTTV emotes, since we use [webcache.py](https://github.com/NMisko/monkalot/blob/master/bot/utilities/webcache.py) set to 3 hours everywhere.

E.g.: You no longer access the Hearthstone cards via a bot attribute (`bot.cards`) but via a method (`bot.getHearthstoneCards()`). This method returns a cached version of the card structure until the timer (3 hours) expires, then it calls the API again. This way that data is always updated.

You can set webcache.py to call a function on the received data, and then return the result of this function. We should move the write-emotes-to-file code into this function, so that after the cache expires, new emotes get written to file.
