### ISSUE TITLE
I have no Cleverbot API Key + One minor issue

### ISSUE THREAD

**Issue by ghostduck** [NMisko/monkalot#4]
Since I have no Cleverbot API Key, output in command.py:1173 will be None and crash afterwards.

Should I just get one API Key to continue testing, or are there any workaround?
I just think that if we are using more API keys, the setup of testing environment will be much more difficult too...

One smaller issue: def setResponses() in bot.py:62 seems never executed (only 1 line can be found by git grep setRes), no need to comment that out?

Lastly ... this is my first coding project in github. I am not sure if I am doing it right or not. Hope that I have not been very annoying or very noobish.

**Comment by CodeMonkey3451** [comment]
Hi ghostduck,

the Cleverbot API Key is needed for the Native Speech of the bot. So if you don't have one (You can get one for free at https://www.cleverbot.com/api/), you have to remove the `class Speech(Command)` from the command pool. 
The best way to do it would be to remove or comment bot.py:512. This way the bot will never use the Speech class and the API is not needed.

The `def setResponses()` in bot.py:62 just got added recently and will be used in the nearer future. It's to set the response file once it has been modified.

It's always fine to ask questions, no harm done! :)

**Comment by ghostduck** [comment]
I briefly checked Speech class in commands.py. It seems if I comment out `cmds.Speech(self)`, the "ban me" part won't work too ... I think I will try to look for old commits and write some codes to workaround it.

Thanks for your kind comment! I have to sleep now and will write codes later.

**Comment by CodeMonkey3451** [comment]
Yes, it might make sense to put the "ban me" part in another class or create a new class for it. That way `class Speech(Command)` is only reserved for the native speech part which uses the Cleverbot API key.

**Comment by ghostduck** [comment]
Seems ok now
