### ISSUE TITLE
match() - Conditions

### ISSUE THREAD

**Issue by CodeMonkey3451** [NMisko/monkalot#8]
So while looking through the code in `commands.py` I noticed we are using almost the exact same commands to check the conditions in `match()`. It starts with `msg.startswith("!cmd ")` and then sometimes have additional conditions like "The second word has to be an emote." / "The line can only contain 3 words.", etc. Some of these condition checks can get a little messy and we are basicly repeating code with different values.

My idea is to use a standardized 'condition - line' method. First we use a function that parses the written line and extracts all the information available (number of words, text for each word, is the word a number/emote?, etc). Then we define specific condition for each class/function ("First word has to be '!<cmd>', second word has to be an emote, etc.). And finaly have a function that returns wether the line matches the condition for the class or not.

1) Write functions that can give you information about a written line. 

	- How many words are in the line? -> n
	- Information about each word:
		- Is the first word a command? (`!<cmd>`)
		- Is the second word an emote/emoji, NOT an emote, a number, etc.
		- Length of a word
		- Total length of the line
	- Maybe structure like: 
		`line = {`
			`"n": "n-words", `
			`"length": "length-line", `
			`"words": [["text": text1, "type": type1, "length": length1], ["text": text2, …], …]`
		`}`
	- types could be:
		0: default (no emote, no number, etc.)
		1: a command (startswith '!' or is in commandlist)
		2: a number
		3: a username (user should be in the channel)
		4: basic twitch emote
		5: basic bttv emote
		6: bttv emoji
		7: channel bttv emote
		8: special emote the user has access to (subscriber-emotes, turbo, etc.)
		ETC.

2.) Then we can define condition for the command. E.g.: 
(Should probably have a better structure)
	`condition = [`
		`[0, {"text": "!call"}],	->	"First word is '!call'."`
		`[1, {"type": ["emote", "emoji"]}, <- Should be able to handle multiple conditions`
		`[3, {"length": "< 10"},	->	"Third word is shorter than 10 letters."`
		`[n, "< 10"]`
	`]`

3.) Then in `match()` we can go like:
	`if check_match(line, cond):`
		`return True`

Instead of making the check for each condition in the match function. It would make the transition from the wording "The second word needs to be a number." into actual conditions easier/more standardized.

**Comment by ghostduck** [comment]
My brief thoughts:

The current command structure is originated from SimpleTwitchBot.
`match()` is called from bot.py in `process_command`, the line `match = cmd.match(self, user, msg)`

I think we can categories commands into 3 types, briefly:

1. commands in simplereply list (Note: I rarely see this used by mods in Zeta's channel ...)

2. something slightly complicated and requires special logic that we need to write (Oralpleasure for example, not really difficult logic but we need to remember the state in monkalot's memory)

3. quite complicated one, like Question command (what is 2Head + 2Head in msg) and Spam command

If I am not mistaken, you want to rework on the `match()` of those in category 2.

My concern is that category 3 wouldn't fit for your proposed change.

So maybe we can have a ...

`QuiteSimpleCommand `class which is inherited from `Command `class, then its `match()` will call something like `common_check()`. Then it will do the default? type of checking we want, while leaving those complicated category 3 commands intact.

**Comment by NMisko** [comment]
This seems too complicated and not really necessary. Having `msg.startswith("!xxxx ")` or `user.permission = ADMIN` in command classes is easy to read and allows one to understand match conditions without having to look up external classes.
